version: '3.8'

services:
  retail-service:
    depends_on:
      - postgres
      - nats-server
    build:
      context: ./retail
    container_name: retail-server
    hostname: retail-server
    networks:
      - mynet
    ports:
      - 80:8080
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_DBNAME=retail
    deploy:
      restart_policy:
        condition: on-failure

  notify-service:
    depends_on:
      - nats-server
    build:
      context: ./notify
    container_name: notify-service
    hostname: notify
    networks:
      - mynet
    deploy:
      restart_policy:
        condition: on-failure

  postgres:
    image: postgres:latest
    networks:
      - mynet
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=retail
      - DATABASE_HOST=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  nats-server:
    image: nats:latest
    hostname: nats-server
    container_name: nats-server
    networks:
      - mynet
    ports:
      - 4222:4222

volumes:
  postgres:

networks:
  mynet:
    driver: bridge
