version: '3.8'

services:
  retail-service:
    depends_on:
      - postgres
      - nats-server
    build:
      context: ./retail
    container_name: retail-server
    hostname: retail-server
    networks:
      - mynet
    ports:
      - 80:8080
    environment:
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DBNAME=${PG_DBNAME}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - JWT_KEY=${JWT_KEY}
    deploy:
      restart_policy:
        condition: on-failure

  notify-service:
    depends_on:
      - nats-server
    build:
      context: ./notify
    container_name: notify-service
    hostname: notify
    networks:
      - mynet
    environment:
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    deploy:
      restart_policy:
        condition: on-failure

  postgres:
    image: postgres:latest
    networks:
      - mynet
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DBNAME}
      - DATABASE_HOST=${PG_HOST}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  nats-server:
    image: nats:latest
    hostname: nats-server
    container_name: nats-server
    networks:
      - mynet
    ports:
      - 4222:4222

volumes:
  postgres:

networks:
  mynet:
    driver: bridge
