name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build-retail-service
        working-directory: ./retail/app
        run: go build -v ./...

      - name: Test-retail-service-business
        working-directory: ./retail/business
        run: go test -v ./...

      - name: Build-notify-service
        working-directory: ./notify
        run: go build -v ./...
